name: torch compile tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to test on
        required: true
      pytorch_nightly:
        description: Whether to use PyTorch nightly (true/false)
        required: false
        default: false
env:
  RUN_SLOW: yes
  IS_GITHUB_CI: '1'
  NVIDIA_DISABLE_REQUIRE: '1'
permissions: {}
jobs:
  run_tests_with_compile:
    runs-on: ubuntu-latest
    env:
      PEFT_DEBUG_WITH_TORCH_COMPILE: 1
      CUDA_VISIBLE_DEVICES: '0'
      TEST_TYPE: single_gpu_huggingface/peft-gpu:latest
      USE_PYTORCH_NIGHTLY: ${{ github.event.inputs.pytorch_nightly }}
    container:
      image: huggingface/peft-gpu:latest
      options: --gpus all --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        ref: ${{ github.event.inputs.branch }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        persist-credentials: false
    - name: Pip install
      run: "source activate peft\npip install -e . --no-deps\npip install pytest-cov\
        \ pytest-reportlog parameterized datasets scipy einops\npip install \"pytest>=7.2.0,<8.0.0\"\
        \ # see: https://github.com/huggingface/transformers/blob/ce4fff0be7f6464d713f7ac3e0bbaafbc6959ae5/setup.py#L148C6-L148C26\n\
        if [ \"${USE_PYTORCH_NIGHTLY}\" = \"true\" ]; then\n  python -m pip install\
        \ --upgrade --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu\n\
        fi\n"
    - name: Test compile with pytest
      run: 'source activate peft

        echo "PEFT_DEBUG_WITH_TORCH_COMPILE=$PEFT_DEBUG_WITH_TORCH_COMPILE"

        make tests_torch_compile

        '
